# Generated by Django 3.2.8 on 2022-06-05 19:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FintnessSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_sub_key', models.CharField(max_length=150, verbose_name='Stripe subscription key')),
                ('stripe_session_key', models.CharField(max_length=150, verbose_name='Stripe session key')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Fitness subscription',
                'verbose_name_plural': 'Fitness subscriptions',
            },
        ),
        migrations.CreateModel(
            name='FitnessClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160, verbose_name='Fitness class name')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug')),
                ('thumbnail', models.ImageField(upload_to='fitness_class_thumbnails', verbose_name='Thumbnail')),
                ('description', models.TextField(verbose_name='Class description')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9]{9,11}$', 'Phone number is not valid.')], verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.CharField(max_length=160, verbose_name='Address')),
                ('attachment', models.FileField(upload_to='fitness_class_attachments', verbose_name='Attachment')),
            ],
            options={
                'verbose_name': 'Fitness class',
                'verbose_name_plural': 'Fitness classes',
            },
        ),
        migrations.CreateModel(
            name='FitnessSubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Plan name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('description', models.TextField(verbose_name='Description')),
                ('stripe_price_id', models.CharField(max_length=50, verbose_name='Stripe price id')),
                ('thumbnail', models.ImageField(upload_to='fitness_plan_thumbnail', verbose_name='Thumbnail')),
            ],
            options={
                'verbose_name': 'Fitness subscription plan',
                'verbose_name_plural': 'Fitness subscription plans',
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=50, verbose_name='Trainer title')),
                ('avatar', models.ImageField(upload_to='avatars', verbose_name='avatar')),
                ('introduction', models.TextField(verbose_name='Introduction')),
                ('personal_summery', models.TextField(verbose_name='Personal summery')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^[0-9]{9,11}$', 'Phone number is not valid.')], verbose_name='Phone Number')),
                ('address', models.CharField(max_length=150, verbose_name='Address')),
            ],
        ),
        migrations.CreateModel(
            name='NutritionPlan',
            fields=[
                ('fitnesssubscriptionplan_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='classes.fitnesssubscriptionplan')),
            ],
            options={
                'verbose_name': 'Nutrition plan',
                'verbose_name_plural': 'Nutrition plans',
            },
            bases=('classes.fitnesssubscriptionplan',),
        ),
        migrations.CreateModel(
            name='NutritionSubscription',
            fields=[
                ('fintnesssubscription_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='classes.fintnesssubscription')),
            ],
            options={
                'verbose_name': 'Nutrition subscription',
                'verbose_name_plural': 'Nutrition subscriptions',
            },
            bases=('classes.fintnesssubscription',),
        ),
        migrations.CreateModel(
            name='TrainerSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=80, verbose_name='Skill')),
                ('efficiency', models.IntegerField(verbose_name='Efficiency')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='classes.trainer')),
            ],
            options={
                'verbose_name': 'Trainer Skill',
                'verbose_name_plural': 'Trainer Skills',
            },
        ),
        migrations.AddField(
            model_name='fintnesssubscription',
            name='fitness_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitness_subscriptions', to='classes.fitnesssubscriptionplan', verbose_name='Fitness Plan'),
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=10, verbose_name='Day')),
                ('start_time', models.TimeField(verbose_name='Start time')),
                ('end_time', models.TimeField(verbose_name='End time')),
                ('fitness_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_schedules', to='classes.fitnessclass', verbose_name='Fitness class')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer', to='classes.trainer', verbose_name='Trainer')),
            ],
            options={
                'verbose_name': 'Class schedule',
                'verbose_name_plural': 'Class schedules',
            },
        ),
    ]
