#! /bin/bash
echo "Exporting the environment variables..."

export EMAIL_HOST_USER=
export EMAIL_HOST_PASSWORD=

export STRIPE_LIVE_SECRET_KEY=sk_live_YOUR_STRIPE_LIVE_SECRET_KEY
export DJSTRIPE_WEBHOOK_SECRET=whsec_xxx

export STRIPE_TEST_SECRET_KEY=
export STRIPE_PUBLIC_KEY=
export DJSTRIPE_FOREIGN_KEY_TO_FIELD=id
export STRIPE_LIVE_MODE=false

export AWS_STORAGE_BUCKET_NAME=
export AWS_ACCESS_KEY_ID=
export AWS_SECRET_ACCESS_KEY=
export AWS_S3_REGION_NAME=

export MAILCHIMP_API_KEY=
export MAILCHIMP_DATA_CENTER=
export MAILCHIMP_EMAIL_LIST_ID=