# Generated by Django 3.2.8 on 2022-06-05 19:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, help_text='Required', max_length=200, verbose_name='Product Title')),
                ('short_description', models.TextField(blank=True, max_length=500, verbose_name='Short Description')),
                ('description', models.TextField(blank=True, help_text='Optional', verbose_name='Product Description')),
                ('additional_information', models.TextField(blank=True, verbose_name='Additional Product Information')),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('regular_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Regular price')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, verbose_name='Discount price')),
                ('stocks', models.IntegerField(default=0, verbose_name='Stocks')),
                ('sale_tag', models.CharField(blank=True, choices=[('SALE', 'SALE'), ('NEW', 'NEW'), ('HOT', 'HOT')], max_length=10, verbose_name='Sale Tag')),
                ('is_active', models.BooleanField(default=True, help_text='Change product visibility', verbose_name='Product visibility')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required and unique', max_length=255, unique=True, verbose_name='Category Name')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='Slug for url')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='images/product_default.png', help_text='Upload a product image', upload_to='products/', verbose_name='image')),
                ('is_feature', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='products.productcategory', verbose_name='Product Categories'),
        ),
    ]
